(function(){
let ps=[],editId=null,viewMode='all',supabase=null;const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function refresh(){ps=await AEROFLEX.getProducts();$('totalArticles').textContent=ps.length;$('availableArticles').textContent=ps.filter(p=>p.variants.some(v=>v.stock>0)).length;$('outArticles').textContent=ps.filter(p=>!p.variants.some(v=>v.stock>0)).length;$('totalCtn').textContent=ps.reduce((s,p)=>s+p.variants.reduce((a,v)=>a+Math.max(0,v.stock||0),0),0);renderTable();}
function renderTable(){const rows=viewMode==='available'?ps.filter(p=>p.variants.some(v=>v.stock>0)):ps;$('actionHead').textContent=viewMode==='available'?'AVAILABLE STOCK ACTIONS':'ALL ITEM ACTIONS';$('adminRows').innerHTML=rows.map(p=>{const av=p.variants.filter(v=>v.stock>0);return `<tr><td><img class="thumb" src="${esc((av[0]||p.variants[0])?.image||p.image||'assets/aeroflex-logo.png')}"></td><td><b>${esc(p.name)}</b><small class="status ${av.length?'ok':'out'}">${av.length?'AVAILABLE':'OUT OF STOCK'}</small></td><td>${esc(p.category)}</td><td>Rs. ${Number(p.price||0).toLocaleString()}</td><td>${viewMode==='available'?av.map(v=>`<span class="ctn-line"><b>${esc(v.name)}</b><strong>${v.stock} CTN</strong></span>`).join(''):'—'}</td><td><button onclick="AEROFLEX_ADMIN.edit('${p.id}')">EDIT</button> ${viewMode==='available'?`<button onclick="AEROFLEX_ADMIN.editStock('${p.id}')">EDIT STOCK</button>`:`<button onclick="AEROFLEX_ADMIN.addStock('${p.id}')">ADD TO STOCK</button>`} <button class="danger" onclick="AEROFLEX_ADMIN.del('${p.id}')">DELETE</button></td></tr>`}).join('')||'<tr><td colspan="6">No articles in this view.</td></tr>';}
function row(v={name:'',image:''}){return `<div class="variant-row"><input class="v-name" placeholder="Colour name (optional)" value="${esc(v.name)}"><input class="v-file" type="file" accept="image/*"><input type="hidden" class="v-image" value="${esc(v.image||'')}"><button type="button" class="remove-v">×</button></div>`;}
function openForm(p){editId=p?.id||null;$('formTitle').textContent=p?'Edit Article':'Add Article';$('name').value=p?.name||'';$('price').value=p?.price||'';$('cat').value=p?.category||'AEROFLEX';$('size').value=p?.size||'Standard';$('condition').value=p?.condition||'10/10';$('description').value=p?.description||'';$('mainImage').value='';$('existingMain').textContent=p?'Existing picture is preserved unless a new picture is selected.':'';const vars=p?.variants||[];$('variantList').innerHTML=vars.map(row).join('');bindRemove();$('productModal').hidden=false;}
function bindRemove(){document.querySelectorAll('.remove-v').forEach(b=>b.onclick=()=>b.parentElement.remove());}
async function submit(e){e.preventDefault();const old=ps.find(x=>String(x.id)===String(editId));const rows=[...document.querySelectorAll('.variant-row')];const mainFile=$('mainImage').files[0];const pId=editId||crypto.randomUUID();let main=old?.image||'';try{if(mainFile)main=await AEROFLEX.uploadImage(mainFile,`${pId}/main-${Date.now()}`);const vars=[];for(const r of rows){const name=r.querySelector('.v-name').value.trim().toUpperCase();if(!name)continue;const file=r.querySelector('.v-file').files[0];let image=r.querySelector('.v-image').value||'';if(file)image=await AEROFLEX.uploadImage(file,`${pId}/${crypto.randomUUID()}`);if(!image)image=main||old?.image||'';const oldv=old?.variants?.find(v=>String(v.name||v.colour_name||'').toUpperCase()===name);vars.push({id:oldv?.id||crypto.randomUUID(),name,openingStock:Number(oldv?.openingStock||0),stock:Number(oldv?.stock||0),image});}
if(!main)main=vars[0]?.image||'';const p={id:pId,name:$('name').value.trim(),price:Number($('price').value||0),category:$('cat').value,size:$('size').value.trim(),condition:$('condition').value.trim(),description:$('description').value.trim(),image:main,variants:vars};if(!p.name)return alert('Article name required.');const result=await AEROFLEX.saveProduct(p);if(result?.error)throw result.error;$('productModal').hidden=true;await refresh();}catch(err){console.error(err);alert('Article save nahi hua. '+(err.message||err));}}
function stockModal(p){const rows=p.variants.map((v,i)=>`<div class="stock-row"><div><b>${esc(v.name)}</b><small>Current: ${Number(v.stock||0)} CTN</small></div><input class="stock-input" data-i="${i}" type="number" min="0" step="1" value="${Number(v.stock||0)}" placeholder="QTY / CTN"></div>`).join('');$('stockTitle').textContent='ADD ARTICLE TO AVAILABLE STOCK — '+p.name;$('stockRows').innerHTML=rows||'<p>No colours added. Article can still be stocked after colours are added in Edit.</p>';$('stockProductId').value=p.id;$('stockModal').hidden=false;}
async function saveStock(){const p=ps.find(x=>String(x.id)===String($('stockProductId').value));if(!p)return;document.querySelectorAll('.stock-input').forEach(inp=>{const v=p.variants[Number(inp.dataset.i)];const q=Math.max(0,parseInt(inp.value||0,10));v.stock=q;if(q>0&&Number(v.openingStock||0)===0)v.openingStock=q;});const r=await AEROFLEX.saveProducts(ps);if(r?.error)return alert('Stock save nahi hua: '+r.error.message);$('stockModal').hidden=true;await refresh();}
async function imageData(url){try{if(!url)return null;if(String(url).startsWith('data:'))return url;const r=await fetch(url,{mode:'cors'});if(!r.ok)throw new Error('Image fetch failed');const b=await r.blob();return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(b);});}catch(e){console.warn('PDF image skipped:',url,e);return null;}}
async function downloadStockPdf(){const rows=ps.filter(p=>p.variants.some(v=>v.stock>0));if(!rows.length)return alert('No available stock.');if(!window.jspdf?.jsPDF)return alert('PDF library load nahi hui. Page refresh karke dobara try karo.');const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4'});for(let i=0;i<rows.length;i++){const p=rows[i],av=p.variants.filter(v=>v.stock>0);if(i)doc.addPage();doc.setTextColor(20,20,20);doc.setFontSize(20);doc.text('AEROFLEX — AVAILABLE STOCK',105,18,{align:'center'});doc.setFontSize(10);doc.text(new Date().toLocaleString(),105,25,{align:'center'});const img=await imageData((av[0]||p.variants[0])?.image||p.image);if(img){try{doc.addImage(img,'JPEG',20,32,80,80,'FAST');}catch(e){console.warn(e);}}doc.setFontSize(18);doc.text(String(p.name||''),110,43,{maxWidth:80});doc.setFontSize(12);doc.text('Price: Rs. '+Number(p.price||0).toLocaleString(),110,51);doc.setFontSize(13);let y=66;for(const v of av){doc.text(String(v.name||'').toUpperCase(),110,y);doc.text(String(v.stock)+' CTN',190,y,{align:'right'});y+=9;}doc.setDrawColor(180,145,65);doc.line(20,122,190,122);doc.setFontSize(9);doc.text('Available colours only — 0 CTN colours are excluded.',20,129);}doc.save('AEROFLEX-AVAILABLE-STOCK.pdf');}
function printStock(){const rows=ps.filter(p=>p.variants.some(v=>v.stock>0));$('printDate').textContent=new Date().toLocaleString();$('printContent').innerHTML=rows.map(p=>{const av=p.variants.filter(v=>v.stock>0);return `<div class="print-product"><img src="${esc((av[0]||p.variants[0])?.image||p.image)}"><div><h2>${esc(p.name)}</h2><p class="print-price">Rs. ${Number(p.price||0).toLocaleString()}</p>${av.map(v=>`<div class="print-colour"><b>${esc(v.name)}</b><span>${v.stock} CTN</span></div>`).join('')}</div></div>`}).join('')||'<p>No available stock.</p>';$('printArea').hidden=false;window.print();setTimeout(()=>$('printArea').hidden=true,700);}
async function loadTestArticles(){
const tests=[
['TEST — ART 27.51','6-9','BLACK',5,'test-01.jpg'],
['TEST — ART 21.49','6-9','ZINK',5,'test-02.jpg'],
['TEST — ART 27.31','6-9','BLACK',3,'test-03.jpg'],
['TEST — ART 21-23','6-9','BLACK',4,'test-04.jpg'],
['TEST — ART 21-22 GOLD','6-9','BROWN',0,'test-05.jpg'],
['TEST — ART 21-22 NEW','6-9','MEHROON',0,'test-06.jpg'],
['TEST — ART 40.38','6-9','BLACK',2,'test-07.jpg'],
['TEST — ART LR.7041','7-10','SILVER',0,'test-08.jpg']
];
if(!confirm('8 test articles add/update karne hain?'))return;
for(let i=0;i<tests.length;i++){const [name,size,colour,stock,file]=tests[i];const id='aeroflex-test-'+String(i+1).padStart(2,'0');const p={id,name,price:0,category:'AEROFLEX',size,condition:'10/10',description:'TEST ARTICLE — temporary testing item.',image:'assets/test-products/'+file,variants:[{id:id+'-v1',name,openingStock:stock,stock,image:'assets/test-products/'+file}]};p.variants[0].name=colour;const r=await AEROFLEX.saveProduct(p);if(r?.error){console.error(r.error);return alert('Test article save nahi hua: '+(r.error.message||r.error));}}await refresh();alert('8 test articles successfully loaded.');}
async function initAuth(){const c=window.AEROFLEX_CONFIG||{};if(window.supabase&&c.SUPABASE_PUBLISHABLE_KEY&&!c.SUPABASE_PUBLISHABLE_KEY.includes('PASTE_')){supabase=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY);const {data}=await supabase.auth.getSession();if(data.session)showDashboard();}else{$('loginMsg').textContent='Secure login setup incomplete.';$('loginBtn').disabled=true;}}
function showDashboard(){$('loginBox').hidden=true;$('dashboard').hidden=false;refresh();}async function login(){if(!supabase)return;const email=$('adminEmail').value.trim(),password=$('adminPassword').value;if(!email||!password)return $('loginMsg').textContent='Email aur password enter karo.';$('loginBtn').disabled=true;const {error}=await supabase.auth.signInWithPassword({email,password});$('loginBtn').disabled=false;if(error)return $('loginMsg').textContent='Login failed: '+error.message;showDashboard();}async function logout(){if(supabase)await supabase.auth.signOut();$('dashboard').hidden=true;$('loginBox').hidden=false;}
window.AEROFLEX_ADMIN={edit:id=>openForm(ps.find(p=>String(p.id)===String(id))),addStock:id=>stockModal(ps.find(p=>String(p.id)===String(id))),editStock:id=>stockModal(ps.find(p=>String(p.id)===String(id))),del:async id=>{if(confirm('Delete this article?')){const r=await AEROFLEX.deleteProduct(id);if(r?.error)alert('Delete nahi hua: '+r.error.message);else await refresh();}}};
document.addEventListener('DOMContentLoaded',()=>{initAuth();$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('addBtn').onclick=()=>openForm();$('duplicateBtn').onclick=()=>openStockPicker();$('closeModal').onclick=()=>$('productModal').hidden=true;$('cancelForm').onclick=()=>$('productModal').hidden=true;$('addVariant').onclick=()=>{if(document.querySelectorAll('.variant-row').length<10){$('variantList').insertAdjacentHTML('beforeend',row());bindRemove();}else alert('Maximum 10 colours per article.');};$('productForm').onsubmit=submit;$('closeStockModal').onclick=()=>$('stockModal').hidden=true;$('cancelStock').onclick=()=>$('stockModal').hidden=true;$('saveStock').onclick=saveStock;$('printBtn').onclick=printStock;$('pdfBtn').onclick=downloadStockPdf;$('testBtn').onclick=loadTestArticles;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');viewMode=t.dataset.mode;renderTable();});});
function openStockPicker(){const list=ps.slice().sort((a,b)=>a.name.localeCompare(b.name));$('stockPickerList').innerHTML=list.map(p=>`<button class="article-pick" type="button" onclick="AEROFLEX_ADMIN.pickStock('${p.id}')"><span>${esc(p.name)}</span><small>${esc(p.category)}</small></button>`).join('')||'<p>No articles found.</p>';$('stockPicker').hidden=false;}
window.AEROFLEX_ADMIN.pickStock=id=>{const p=ps.find(x=>String(x.id)===String(id));$('stockPicker').hidden=true;if(p)stockModal(p);};
})();
