(function(){
const KEY="aeroflex_products", STOCK_KEY="aeroflex_stock";
function products(){try{let x=localStorage.getItem(KEY);return x?JSON.parse(x):window.AEROFLEX?.getProducts?.()||[];}catch(e){return [];}}
function stockMap(){try{return JSON.parse(localStorage.getItem(STOCK_KEY)||"{}");}catch(e){return {};}}
function saveStock(m){localStorage.setItem(STOCK_KEY,JSON.stringify(m));}
function stockKey(pid,name){return pid+"::"+String(name||"").trim().toUpperCase();}
function getStock(pid,name){return Number(stockMap()[stockKey(pid,name)]||0);}
function ensureStockMap(ps){let m=stockMap(), changed=false; ps.forEach(p=>(p.variants||[]).forEach(v=>{const k=stockKey(p.id,v.name);if(!(k in m)){m[k]=Math.max(0,Number(v.stock||0));changed=true;}}));if(changed)saveStock(m);return m;}
function save(ps){localStorage.setItem(KEY,JSON.stringify(ps));}
let ps=products(), editId=null; ensureStockMap(ps);
const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));}
function refresh(){
 ps=products();
 const sm=ensureStockMap(ps);
 $("totalArticles").textContent=ps.length;
 $("availableArticles").textContent=ps.filter(p=>p.variants.some(v=>Number(sm[stockKey(p.id,v.name)]||0)>0)).length;
 $("outArticles").textContent=ps.filter(p=>!p.variants.some(v=>Number(sm[stockKey(p.id,v.name)]||0)>0)).length;
 $("totalCtn").textContent=ps.reduce((s,p)=>s+p.variants.reduce((a,v)=>a+Math.max(0,Number(sm[stockKey(p.id,v.name)]||0)),0),0);
 $("allItemRows").innerHTML=ps.map(p=>`<tr><td><img class="thumb" src="${esc(p.image)}" alt=""></td><td><b>${esc(p.name)}</b><br><small>Rs. ${Number(p.price).toLocaleString()}</small></td><td>${esc(p.category)}</td><td>${p.variants.map(v=>`<span class="colour-pill">${esc(v.name)}</span>`).join(" ")}</td><td><button onclick="AEROFLEX_ADMIN.edit('${esc(p.id)}')">EDIT</button> <button class="danger" onclick="AEROFLEX_ADMIN.del('${esc(p.id)}')">DELETE</button></td></tr>`).join("") || `<tr><td colspan="5">No items yet.</td></tr>`;
 $("stockRows").innerHTML=ps.filter(p=>p.variants.some(v=>Number(sm[stockKey(p.id,v.name)]||0)>0)).map(p=>{const av=p.variants.filter(v=>Number(sm[stockKey(p.id,v.name)]||0)>0);return `<tr><td><img class="thumb" src="${esc(p.image)}" alt=""></td><td><b>${esc(p.name)}</b><br><small>${esc(p.category)}</small></td><td>${av.map(v=>`<div class="stock-line"><b>${esc(v.name)}</b><span>${Number(sm[stockKey(p.id,v.name)]||0).toLocaleString()} CTN</span></div>`).join("")}</td></tr>`}).join("") || `<tr><td colspan="3">No available stock.</td></tr>`;
}
function variantRow(v={name:"",image:""}){const id="v_"+Math.random().toString(36).slice(2);return `<div class="variant-row" data-vid="${id}"><input class="v-name" placeholder="Colour name e.g. BLACK" value="${esc(v.name)}" required><input class="v-file" type="file" accept="image/*"><input type="hidden" class="v-image" value="${esc(v.image)}"><button type="button" class="remove-v">×</button></div>`;}
function openForm(p){editId=p?.id||null;$("formTitle").textContent=p?"Edit Article":"Add Article";$("productId").value=editId||"";$("name").value=p?.name||"";$("price").value=p?.price||"";$("cat").value=p?.category||"AEROFLEX";$("size").value=p?.size||"Standard";$("condition").value=p?.condition||"10/10";$("description").value=p?.description||"";$("mainImage").value="";$("variantList").innerHTML=(p?.variants||[{name:"",image:""}]).map(variantRow).join("");bindVariantRemove();$("productModal").hidden=false;}
function bindVariantRemove(){document.querySelectorAll(".remove-v").forEach(b=>b.onclick=()=>b.parentElement.remove());}
function readFile(file){return new Promise(r=>{if(!file)return r(null);const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(file);});}
async function submit(e){e.preventDefault();const old=ps.find(x=>x.id===editId),oldStock=stockMap(),main=await readFile($("mainImage").files[0]);const rows=[...document.querySelectorAll(".variant-row")];if(!rows.length){alert("Add at least one colour.");return;}const vars=[];for(const row of rows){const name=row.querySelector(".v-name").value.trim().toUpperCase();const file=row.querySelector(".v-file").files[0];const image=await readFile(file);if(!name){alert("Every colour needs a name.");return;}vars.push({name,image:image||row.querySelector(".v-image").value||main||old?.image||"assets/aeroflex-logo.png"});}const p={id:editId||("p_"+Date.now()),name:$("name").value.trim(),price:Number($("price").value||0),category:$("cat").value,size:$("size").value.trim(),condition:$("condition").value.trim(),description:$("description").value.trim(),image:main||old?.image||vars[0].image,variants:vars};if(editId){const next={...oldStock};(old?.variants||[]).forEach((ov,i)=>{const nv=vars[i];if(nv){const oldK=stockKey(editId,ov.name),newK=stockKey(editId,nv.name);if(!(newK in next) && oldK in next)next[newK]=next[oldK];}});saveStock(next);}ps=editId?ps.map(x=>x.id===editId?p:x):[...ps,p];save(ps);ensureStockMap(ps);$("productModal").hidden=true;refresh();}
function openTransfer(){ps=products();if(!ps.length){alert("Add an item first.");return;}$("transferItem").innerHTML=ps.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join("");updateTransferColours();$("transferQty").value="";$("transferModal").hidden=false;}
function updateTransferColours(){const p=ps.find(x=>x.id===$("transferItem").value)||ps[0],sm=ensureStockMap(ps);$("transferColour").innerHTML=(p?.variants||[]).map(v=>`<option value="${esc(v.name)}">${esc(v.name)} — current ${Number(sm[stockKey(p.id,v.name)]||0).toLocaleString()} CTN</option>`).join("");updateTransferPreview();}
function updateTransferPreview(){const p=ps.find(x=>x.id===$("transferItem").value),v=p?.variants.find(x=>x.name===$("transferColour").value),sm=ensureStockMap(ps);if(!v){$("transferPreview").textContent="";return;}$("transferPreview").innerHTML=`Current available: <b>${Number(sm[stockKey(p.id,v.name)]||0).toLocaleString()} CTN</b>`;}
function doTransfer(e){e.preventDefault();const p=ps.find(x=>x.id===$("transferItem").value);const v=p?.variants.find(x=>x.name===$("transferColour").value);const qty=parseInt($("transferQty").value||0,10);if(!p||!v||qty<1){alert("Enter a valid quantity.");return;}const sm=ensureStockMap(ps);const k=stockKey(p.id,v.name);sm[k]=Math.max(0,Number(sm[k]||0))+qty;saveStock(sm);refresh();$("transferModal").hidden=true;alert(`${qty} CTN added to ${p.name} — ${v.name}.`);}
function printStock(){const sm=ensureStockMap(ps);const rows=ps.filter(p=>p.variants.some(v=>Number(sm[stockKey(p.id,v.name)]||0)>0));$("printDate").textContent=new Date().toLocaleString();$("printContent").innerHTML=rows.map(p=>{const av=p.variants.filter(v=>Number(sm[stockKey(p.id,v.name)]||0)>0);return `<div class="print-product"><img src="${esc(p.image)}" alt=""><div><h2>${esc(p.name)}</h2><p class="print-price">Rs. ${Number(p.price).toLocaleString()}</p>${av.map(v=>`<div class="print-colour"><b>${esc(v.name)}</b><span>${Number(sm[stockKey(p.id,v.name)]||0).toLocaleString()} CTN</span></div>`).join("")}</div></div>`}).join("")||"<p>No available stock.</p>";$("printArea").hidden=false;window.print();setTimeout(()=>{$("printArea").hidden=true;},500);}
function pdf(){printStock();}
function login(){const email=$("adminEmail").value.trim(),pass=$("adminPassword").value;if(!email||!pass){$("loginMsg").textContent="Enter admin email and password.";return;}$("loginBox").hidden=true;$("dashboard").hidden=false;refresh();}
window.AEROFLEX_ADMIN={edit:id=>openForm(ps.find(p=>p.id===id)),del:id=>{if(confirm("Delete this article?")){const keep=ps.filter(p=>p.id!==id);const sm=stockMap();Object.keys(sm).forEach(k=>{if(k.startsWith(id+"::"))delete sm[k];});saveStock(sm);save(keep);ps=keep;refresh();}}};
document.addEventListener("DOMContentLoaded",()=>{$("loginBtn").onclick=login;$(addBtn).onclick=()=>openForm();$("transferBtn").onclick=openTransfer;$(closeTransfer).onclick=()=>$("transferModal").hidden=true;$(cancelTransfer).onclick=()=>$("transferModal").hidden=true;$(transferItem).onchange=updateTransferColours;$(transferColour).onchange=updateTransferPreview;$(transferForm).onsubmit=doTransfer;$(closeModal).onclick=()=>$("productModal").hidden=true;$(cancelForm).onclick=()=>$("productModal").hidden=true;$(addVariant).onclick=()=>{if(document.querySelectorAll(".variant-row").length<10){$("variantList").insertAdjacentHTML("beforeend",variantRow());bindVariantRemove();}else alert("Maximum 10 colours per article.");};$("productForm").onsubmit=submit;$("printBtn").onclick=printStock;$("pdfBtn").onclick=pdf;});
})();
