(function(){
const DEMO=[{id:'af01',name:'AEROFLEX 01',price:2500,category:'AEROFLEX',size:'Standard',condition:'10/10',description:'Premium AEROFLEX cappal / sandal article.',image:'assets/aeroflex-logo.png',variants:[{id:'v1',name:'BLACK',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'},{id:'v2',name:'BROWN',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'},{id:'v3',name:'NAVY',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'},{id:'v4',name:'TAN',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'}]},{id:'ll01',name:'LOOK LASTER 01',price:2800,category:'LOOK LASTER',size:'Standard',condition:'10/10',description:'Premium LOOK LASTER article.',image:'assets/aeroflex-logo.png',variants:[{id:'v5',name:'BLACK',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'},{id:'v6',name:'BROWN',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'}]},{id:'ls01',name:'LS 01',price:2200,category:'LS',size:'Standard',condition:'10/10',description:'Premium LS article.',image:'assets/aeroflex-logo.png',variants:[{id:'v7',name:'BLACK',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'},{id:'v8',name:'GREY',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'}]},{id:'cam01',name:'CAMLO 01',price:2600,category:'CAMLO',size:'Standard',condition:'10/10',description:'Premium CAMLO article.',image:'assets/aeroflex-logo.png',variants:[{id:'v9',name:'BLACK',openingStock:0,stock:0,image:'assets/aeroflex-logo.png'}]}];
function normalize(ps){return(ps||[]).map(p=>({...p,variants:(p.variants||[]).map(v=>({...v,openingStock:Number(v.openingStock??0),stock:Number(v.stock??0)}))}));}
function getProducts(){try{const x=localStorage.getItem('aeroflex_products');return normalize(x?JSON.parse(x):DEMO)}catch(e){return normalize(DEMO)}} function saveProducts(ps){localStorage.setItem('aeroflex_products',JSON.stringify(normalize(ps)));}
function waLink(p,v,request){const n=(window.AEROFLEX_CONFIG?.WHATSAPP_NUMBER||'').replace(/\D/g,'');if(!n)return '#';const text=`ASALAMUALAIKUM AEROFLEX,\n\nI want to ${request?'request':'order'}:\n\nProduct: ${p.name}\n\nColour: ${v?.name||'Not selected'}\n\nPrice: Rs. ${Number(p.price||0).toLocaleString()}\n\nSize: ${p.size||'Standard'}\n\nCondition: ${p.condition||'10/10'}\n\nName:\n\nPhone:\n\nAddress:\n\nJazakAllah Khair.`;return `https://wa.me/${n}?text=${encodeURIComponent(text)}`;}
function productCard(p,mode){const avail=p.variants.filter(v=>v.stock>0),visible=mode==='available'?avail:p.variants;if(mode==='available'&&!avail.length)return '';const first=visible[0]||p.variants[0];return `<article class="product-card"><a href="product.html?id=${encodeURIComponent(p.id)}&mode=${mode}"><div class="product-img"><img src="${first?.image||p.image}" alt="${p.name}">${mode==='all'&&!avail.length?'<span class="badge">ORDER ON REQUEST</span>':''}</div><div class="product-info"><h3>${p.name}</h3><span>${p.category}</span><strong>Rs. ${Number(p.price||0).toLocaleString()}</strong>${mode==='available'?`<small class="ctn-pill">${avail.map(v=>v.name).join(' • ')}</small>`:`<small>${p.variants.map(v=>v.name).join(' • ')}</small>`}</div></a></article>`;}
function renderShop({mode}){const grid=document.getElementById('productGrid'),search=document.getElementById('search'),category=document.getElementById('category'),sort=document.getElementById('sort');const params=new URLSearchParams(location.search);if(params.get('category'))category.value=params.get('category');function go(){let ps=getProducts();const q=(search.value||'').toLowerCase();ps=ps.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!category.value||p.category===category.value));if(mode==='available')ps=ps.filter(p=>p.variants.some(v=>v.stock>0));ps.sort((a,b)=>sort.value==='za'?b.name.localeCompare(a.name):sort.value==='low'?a.price-b.price:sort.value==='high'?b.price-a.price:a.name.localeCompare(b.name));grid.innerHTML=ps.map(p=>productCard(p,mode)).join('')||'<div class="empty">No articles found.</div>';}[search,category,sort].forEach(x=>x.addEventListener('input',go));go();}
function renderProduct(){const id=new URLSearchParams(location.search).get('id'),mode=new URLSearchParams(location.search).get('mode')||'all',p=getProducts().find(x=>x.id===id),el=document.getElementById('productDetail');if(!p){el.innerHTML='<h1>Product not found</h1>';return;}let selected=(mode==='available'?p.variants.find(v=>v.stock>0):p.variants[0])||p.variants[0];const draw=()=>{const vars=mode==='available'?p.variants.filter(v=>v.stock>0):p.variants;el.innerHTML=`<div class="detail-media"><img src="${selected?.image||p.image}" alt="${p.name}"></div><div class="detail-copy"><span class="eyebrow">${p.category}</span><h1>${p.name}</h1><h2>Rs. ${Number(p.price).toLocaleString()}</h2><p>${p.description||''}</p><div class="meta"><span>Size: ${p.size}</span><span>Condition: ${p.condition}</span></div><h3>COLOUR: <b>${selected?.name||'-'}</b></h3><div class="variants">${vars.map((v,i)=>`<button class="variant ${v===selected?'selected':''}" data-id="${v.id}">${v.name}</button>`).join('')}</div><a class="btn gold order-btn" href="${waLink(p,selected,mode==='all'&&selected?.stock<=0)}" target="_blank">${mode==='available'?'ORDER ON WHATSAPP':'ORDER ON WHATSAPP / REQUEST'}</a></div>`;el.querySelectorAll('.variant').forEach(b=>b.onclick=()=>{selected=p.variants.find(v=>v.id===b.dataset.id)||selected;draw();});};draw();}
function setup(){document.querySelectorAll('#headerWa,#heroWa,#ctaWa').forEach(a=>a.href=waLink({name:'AEROFLEX'},null,true));const f=document.getElementById('featuredGrid');if(f)f.innerHTML=getProducts().map(p=>productCard(p,'all')).join('');document.querySelectorAll('#year').forEach(x=>x.textContent=new Date().getFullYear());}
window.AEROFLEX={getProducts,saveProducts,renderShop,renderProduct,waLink};document.addEventListener('DOMContentLoaded',setup);
})();
